package com.jimi.uw_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;


/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSampleTaskMaterialRecord<M extends BaseSampleTaskMaterialRecord<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M) this;
	}


	public java.lang.Integer getId() {
		return getInt("id");
	}


	public M setMaterialId(java.lang.String materialId) {
		set("material_id", materialId);
		return (M) this;
	}


	public java.lang.String getMaterialId() {
		return getStr("material_id");
	}


	public M setTaskId(java.lang.Integer taskId) {
		set("task_id", taskId);
		return (M) this;
	}


	public java.lang.Integer getTaskId() {
		return getInt("task_id");
	}


	public M setBoxId(java.lang.Integer boxId) {
		set("box_id", boxId);
		return (M) this;
	}


	public java.lang.Integer getBoxId() {
		return getInt("box_id");
	}


	public M setIsScaned(java.lang.Boolean isScaned) {
		set("is_scaned", isScaned);
		return (M) this;
	}


	public java.lang.Boolean getIsScaned() {
		return get("is_scaned");
	}

}
