package com.jimi.uw_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGoodsLocation<M extends BaseGoodsLocation<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setWindowId(java.lang.Integer windowId) {
		set("window_id", windowId);
		return (M)this;
	}
	
	public java.lang.Integer getWindowId() {
		return getInt("window_id");
	}

	public M setXPosition(java.lang.Integer xPosition) {
		set("x_position", xPosition);
		return (M)this;
	}
	
	public java.lang.Integer getXPosition() {
		return getInt("x_position");
	}

	public M setYPosition(java.lang.Integer yPosition) {
		set("y_position", yPosition);
		return (M)this;
	}
	
	public java.lang.Integer getYPosition() {
		return getInt("y_position");
	}

	public M setZPosition(java.lang.Integer zPosition) {
		set("z_position", zPosition);
		return (M)this;
	}
	
	public java.lang.Integer getZPosition() {
		return getInt("z_position");
	}

	public M setEnabled(java.lang.Boolean enabled) {
		set("enabled", enabled);
		return (M)this;
	}
	
	public java.lang.Boolean getEnabled() {
		return get("enabled");
	}

}
