package com.jimi.uw_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMaterialBoxDetail<M extends BaseMaterialBoxDetail<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setBoxId(java.lang.Integer boxId) {
		set("box_id", boxId);
		return (M)this;
	}
	
	public java.lang.Integer getBoxId() {
		return getInt("box_id");
	}

	public M setXPosition(java.lang.Integer xPosition) {
		set("x_position", xPosition);
		return (M)this;
	}
	
	public java.lang.Integer getXPosition() {
		return getInt("x_position");
	}

	public M setYPosition(java.lang.Integer yPosition) {
		set("y_position", yPosition);
		return (M)this;
	}
	
	public java.lang.Integer getYPosition() {
		return getInt("y_position");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
