package com.jimi.uw_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;


/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSampleTaskItem<M extends BaseSampleTaskItem<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M) this;
	}


	public java.lang.Integer getId() {
		return getInt("id");
	}


	public M setTaskId(java.lang.Integer taskId) {
		set("task_id", taskId);
		return (M) this;
	}


	public java.lang.Integer getTaskId() {
		return getInt("task_id");
	}


	public M setMaterialTypeId(java.lang.Integer materialTypeId) {
		set("material_type_id", materialTypeId);
		return (M) this;
	}


	public java.lang.Integer getMaterialTypeId() {
		return getInt("material_type_id");
	}


	public M setStoreQuantity(java.lang.Integer storeQuantity) {
		set("store_quantity", storeQuantity);
		return (M) this;
	}


	public java.lang.Integer getStoreQuantity() {
		return getInt("store_quantity");
	}


	public M setScanQuantity(java.lang.Integer scanQuantity) {
		set("scan_quantity", scanQuantity);
		return (M) this;
	}


	public java.lang.Integer getScanQuantity() {
		return getInt("scan_quantity");
	}


	public M setSingularOutQuantity(java.lang.Integer singularOutQuantity) {
		set("singular_out_quantity", singularOutQuantity);
		return (M) this;
	}


	public java.lang.Integer getSingularOutQuantity() {
		return getInt("singular_out_quantity");
	}


	public M setRegularOutQuantity(java.lang.Integer regularOutQuantity) {
		set("regular_out_quantity", regularOutQuantity);
		return (M) this;
	}


	public java.lang.Integer getRegularOutQuantity() {
		return getInt("regular_out_quantity");
	}


	public M setLostOutQuantity(java.lang.Integer lostOutQuantity) {
		set("lost_out_quantity", lostOutQuantity);
		return (M) this;
	}


	public java.lang.Integer getLostOutQuantity() {
		return getInt("lost_out_quantity");
	}

}
