package com.jimi.uw_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({ "serial", "unchecked" })
public abstract class BaseExternalInventoryLog<M extends BaseExternalInventoryLog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M) this;
	}


	public java.lang.Integer getId() {
		return getInt("id");
	}


	public M setTaskId(java.lang.Integer taskId) {
		set("task_id", taskId);
		return (M) this;
	}


	public java.lang.Integer getTaskId() {
		return getInt("task_id");
	}


	public M setMaterialTypeId(java.lang.Integer materialTypeId) {
		set("material_type_id", materialTypeId);
		return (M) this;
	}


	public java.lang.Integer getMaterialTypeId() {
		return getInt("material_type_id");
	}


	public M setWhId(java.lang.Integer whId) {
		set("wh_id", whId);
		return (M) this;
	}


	public java.lang.Integer getWhId() {
		return getInt("wh_id");
	}


	public M setBeforeNum(java.lang.Integer beforeNum) {
		set("before_num", beforeNum);
		return (M) this;
	}


	public java.lang.Integer getBeforeNum() {
		return getInt("before_num");
	}


	public M setActuralNum(java.lang.Integer acturalNum) {
		set("actural_num", acturalNum);
		return (M) this;
	}


	public java.lang.Integer getActuralNum() {
		return getInt("actural_num");
	}


	public M setDifferentNum(java.lang.Integer differentNum) {
		set("different_num", differentNum);
		return (M) this;
	}


	public java.lang.Integer getDifferentNum() {
		return getInt("different_num");
	}


	public M setMaterialReturnNum(java.lang.Integer materialReturnNum) {
		set("material_return_num", materialReturnNum);
		return (M) this;
	}


	public java.lang.Integer getMaterialReturnNum() {
		return getInt("material_return_num");
	}


	public M setInventoryOperatior(java.lang.String inventoryOperatior) {
		set("inventory_operatior", inventoryOperatior);
		return (M) this;
	}


	public java.lang.String getInventoryOperatior() {
		return getStr("inventory_operatior");
	}


	public M setInventoryTime(java.util.Date inventoryTime) {
		set("inventory_time", inventoryTime);
		return (M) this;
	}


	public java.util.Date getInventoryTime() {
		return get("inventory_time");
	}


	public M setCoverOperatior(java.lang.String coverOperatior) {
		set("cover_operatior", coverOperatior);
		return (M) this;
	}


	public java.lang.String getCoverOperatior() {
		return getStr("cover_operatior");
	}


	public M setCoverTime(java.util.Date coverTime) {
		set("cover_time", coverTime);
		return (M) this;
	}


	public java.util.Date getCoverTime() {
		return get("cover_time");
	}


	public M setEnabled(java.lang.Boolean enabled) {
		set("enabled", enabled);
		return (M) this;
	}


	public java.lang.Boolean getEnabled() {
		return get("enabled");
	}

}
