package com.jimi.uw_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBoxPositionTaskItem<M extends BaseBoxPositionTaskItem<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setX1(java.lang.Integer x1) {
		set("x1", x1);
		return (M)this;
	}
	
	public java.lang.Integer getX1() {
		return getInt("x1");
	}

	public M setY1(java.lang.Integer y1) {
		set("y1", y1);
		return (M)this;
	}
	
	public java.lang.Integer getY1() {
		return getInt("y1");
	}

	public M setZ1(java.lang.Integer z1) {
		set("z1", z1);
		return (M)this;
	}
	
	public java.lang.Integer getZ1() {
		return getInt("z1");
	}

	public M setX2(java.lang.Integer x2) {
		set("x2", x2);
		return (M)this;
	}
	
	public java.lang.Integer getX2() {
		return getInt("x2");
	}

	public M setY2(java.lang.Integer y2) {
		set("y2", y2);
		return (M)this;
	}
	
	public java.lang.Integer getY2() {
		return getInt("y2");
	}

	public M setZ2(java.lang.Integer z2) {
		set("z2", z2);
		return (M)this;
	}
	
	public java.lang.Integer getZ2() {
		return getInt("z2");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setRobotId(java.lang.Integer robotId) {
		set("robot_id", robotId);
		return (M)this;
	}
	
	public java.lang.Integer getRobotId() {
		return getInt("robot_id");
	}

	public M setBindId(java.lang.Integer bindId) {
		set("bind_id", bindId);
		return (M)this;
	}
	
	public java.lang.Integer getBindId() {
		return getInt("bind_id");
	}

	public M setBindTaskId(java.lang.Integer bindTaskId) {
		set("bind_task_id", bindTaskId);
		return (M)this;
	}
	
	public java.lang.Integer getBindTaskId() {
		return getInt("bind_task_id");
	}

}
