package com.jimi.uw_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseExternalWhLog<M extends BaseExternalWhLog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setMaterialTypeId(java.lang.Integer materialTypeId) {
		set("material_type_id", materialTypeId);
		return (M)this;
	}
	
	public java.lang.Integer getMaterialTypeId() {
		return getInt("material_type_id");
	}

	public M setTaskId(java.lang.Integer taskId) {
		set("task_id", taskId);
		return (M)this;
	}
	
	public java.lang.Integer getTaskId() {
		return getInt("task_id");
	}

	public M setQuantity(java.lang.Integer quantity) {
		set("quantity", quantity);
		return (M)this;
	}
	
	public java.lang.Integer getQuantity() {
		return getInt("quantity");
	}

	public M setSourceWh(java.lang.Integer sourceWh) {
		set("source_wh", sourceWh);
		return (M)this;
	}
	
	public java.lang.Integer getSourceWh() {
		return getInt("source_wh");
	}

	public M setDestination(java.lang.Integer destination) {
		set("destination", destination);
		return (M)this;
	}
	
	public java.lang.Integer getDestination() {
		return getInt("destination");
	}

	public M setOperatior(java.lang.String operatior) {
		set("operatior", operatior);
		return (M)this;
	}
	
	public java.lang.String getOperatior() {
		return getStr("operatior");
	}

	public M setTime(java.util.Date time) {
		set("time", time);
		return (M)this;
	}
	
	public java.util.Date getTime() {
		return get("time");
	}

}
