package com.jimi.uw_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;


/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseInventoryTaskBaseInfo<M extends BaseInventoryTaskBaseInfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M) this;
	}


	public java.lang.Integer getId() {
		return getInt("id");
	}


	public M setTaskId(java.lang.Integer taskId) {
		set("task_id", taskId);
		return (M) this;
	}


	public java.lang.Integer getTaskId() {
		return getInt("task_id");
	}


	public M setDestinationId(java.lang.Integer destinationId) {
		set("destination_id", destinationId);
		return (M) this;
	}


	public java.lang.Integer getDestinationId() {
		return getInt("destination_id");
	}


	public M setCheckTime(java.util.Date checkTime) {
		set("check_time", checkTime);
		return (M) this;
	}


	public java.util.Date getCheckTime() {
		return get("check_time");
	}


	public M setCheckOperator(java.lang.String checkOperator) {
		set("check_operator", checkOperator);
		return (M) this;
	}


	public java.lang.String getCheckOperator() {
		return getStr("check_operator");
	}

}
