package com.jimi.uw_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePdaUploadLog<M extends BasePdaUploadLog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setParameter(java.lang.String parameter) {
		set("parameter", parameter);
		return (M)this;
	}
	
	public java.lang.String getParameter() {
		return getStr("parameter");
	}

	public M setResponse(java.lang.String response) {
		set("response", response);
		return (M)this;
	}
	
	public java.lang.String getResponse() {
		return getStr("response");
	}

	public M setTaskId(java.lang.Integer taskId) {
		set("task_id", taskId);
		return (M)this;
	}
	
	public java.lang.Integer getTaskId() {
		return getInt("task_id");
	}

}
