package com.jimi.uw_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTaskLog<M extends BaseTaskLog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setMaterialId(java.lang.String materialId) {
		set("material_id", materialId);
		return (M)this;
	}
	
	public java.lang.String getMaterialId() {
		return getStr("material_id");
	}

	public M setPackingListItemId(java.lang.Integer packingListItemId) {
		set("packing_list_item_id", packingListItemId);
		return (M)this;
	}
	
	public java.lang.Integer getPackingListItemId() {
		return getInt("packing_list_item_id");
	}

	public M setQuantity(java.lang.Integer quantity) {
		set("quantity", quantity);
		return (M)this;
	}
	
	public java.lang.Integer getQuantity() {
		return getInt("quantity");
	}

	public M setOperator(java.lang.String operator) {
		set("operator", operator);
		return (M)this;
	}
	
	public java.lang.String getOperator() {
		return getStr("operator");
	}

	public M setAuto(java.lang.Boolean auto) {
		set("auto", auto);
		return (M)this;
	}
	
	public java.lang.Boolean getAuto() {
		return get("auto");
	}

	public M setTime(java.util.Date time) {
		set("time", time);
		return (M)this;
	}
	
	public java.util.Date getTime() {
		return get("time");
	}

	public M setDestination(java.lang.Integer destination) {
		set("destination", destination);
		return (M)this;
	}
	
	public java.lang.Integer getDestination() {
		return getInt("destination");
	}
}
