package com.jimi.uw_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({ "serial", "unchecked" })
public abstract class BaseEfficiency<M extends BaseEfficiency<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M) this;
	}


	public java.lang.Integer getId() {
		return getInt("id");
	}


	public M setUid(java.lang.String uid) {
		set("uid", uid);
		return (M) this;
	}


	public java.lang.String getUid() {
		return getStr("uid");
	}


	public M setYear(java.lang.Integer year) {
		set("year", year);
		return (M) this;
	}


	public java.lang.Integer getYear() {
		return getInt("year");
	}


	public M setMonth(java.lang.Integer month) {
		set("month", month);
		return (M) this;
	}


	public java.lang.Integer getMonth() {
		return getInt("month");
	}


	public M setOperationType(java.lang.Integer operationType) {
		set("operation_type", operationType);
		return (M) this;
	}


	public java.lang.Integer getOperationType() {
		return getInt("operation_type");
	}


	public M setBoxType(java.lang.Integer boxType) {
		set("box_type", boxType);
		return (M) this;
	}


	public java.lang.Integer getBoxType() {
		return getInt("box_type");
	}


	public M setDeltaTime(java.lang.Long deltaTime) {
		set("delta_time", deltaTime);
		return (M) this;
	}


	public java.lang.Long getDeltaTime() {
		return getLong("delta_time");
	}


	public M setDishNum(java.lang.Integer dishNum) {
		set("dish_num", dishNum);
		return (M) this;
	}


	public java.lang.Integer getDishNum() {
		return getInt("dish_num");
	}

}
