package com.jimi.uw_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({ "serial", "unchecked" })
public abstract class BaseSupplier<M extends BaseSupplier<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M) this;
	}


	public java.lang.Integer getId() {
		return getInt("id");
	}


	public M setName(java.lang.String name) {
		set("name", name);
		return (M) this;
	}


	public java.lang.String getName() {
		return getStr("name");
	}


	public M setEnabled(java.lang.Boolean enabled) {
		set("enabled", enabled);
		return (M) this;
	}


	public java.lang.Boolean getEnabled() {
		return get("enabled");
	}


	public M setCompanyId(java.lang.Integer companyId) {
		set("company_id", companyId);
		return (M) this;
	}


	public java.lang.Integer getCompanyId() {
		return getInt("company_id");
	}

}
