package com.jimi.uw_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({ "serial", "unchecked" })
public abstract class BaseTask<M extends BaseTask<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M) this;
	}


	public java.lang.Integer getId() {
		return getInt("id");
	}


	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M) this;
	}


	public java.lang.Integer getType() {
		return getInt("type");
	}


	public M setFileName(java.lang.String fileName) {
		set("file_name", fileName);
		return (M) this;
	}


	public java.lang.String getFileName() {
		return getStr("file_name");
	}


	public M setWindow(java.lang.Integer window) {
		set("window", window);
		return (M) this;
	}


	public java.lang.Integer getWindow() {
		return getInt("window");
	}


	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M) this;
	}


	public java.lang.Integer getState() {
		return getInt("state");
	}


	public M setPriority(java.lang.Integer priority) {
		set("priority", priority);
		return (M) this;
	}


	public java.lang.Integer getPriority() {
		return getInt("priority");
	}


	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M) this;
	}


	public java.util.Date getCreateTime() {
		return get("create_time");
	}


	public M setSupplier(java.lang.Integer supplier) {
		set("supplier", supplier);
		return (M) this;
	}


	public java.lang.Integer getSupplier() {
		return getInt("supplier");
	}


	public M setDestination(java.lang.Integer destination) {
		set("destination", destination);
		return (M) this;
	}


	public java.lang.Integer getDestination() {
		return getInt("destination");
	}


	public M setStartTime(java.util.Date startTime) {
		set("start_time", startTime);
		return (M) this;
	}


	public java.util.Date getStartTime() {
		return get("start_time");
	}


	public M setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
		return (M) this;
	}


	public java.util.Date getEndTime() {
		return get("end_time");
	}


	public M setIsInventoryApply(java.lang.Boolean isInventoryApply) {
		set("is_inventory_apply", isInventoryApply);
		return (M) this;
	}


	public java.lang.Boolean getIsInventoryApply() {
		return get("is_inventory_apply");
	}


	public M setInventoryTaskId(java.lang.Integer inventoryTaskId) {
		set("inventory_task_id", inventoryTaskId);
		return (M) this;
	}


	public java.lang.Integer getInventoryTaskId() {
		return getInt("inventory_task_id");
	}


	public M setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
		return (M) this;
	}


	public java.lang.String getRemarks() {
		return getStr("remarks");
	}


	public M setWarehouseType(java.lang.Integer warehouseType) {
		set("warehouse_type", warehouseType);
		return (M) this;
	}


	public java.lang.Integer getWarehouseType() {
		return getInt("warehouse_type");
	}


	public java.lang.Boolean getIsDeducted() {
		return get("is_deducted");
	}


	public M setIsDeducted(java.lang.Boolean isDeducted) {
		set("is_deducted", isDeducted);
		return (M) this;
	}
}
