package com.jimi.uw_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSampleOutRecord<M extends BaseSampleOutRecord<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSampleTaskItemId(java.lang.Integer sampleTaskItemId) {
		set("sample_task_item_id", sampleTaskItemId);
		return (M)this;
	}
	
	public java.lang.Integer getSampleTaskItemId() {
		return getInt("sample_task_item_id");
	}

	public M setMaterialId(java.lang.String materialId) {
		set("material_id", materialId);
		return (M)this;
	}
	
	public java.lang.String getMaterialId() {
		return getStr("material_id");
	}

	public M setQuantity(java.lang.Integer quantity) {
		set("quantity", quantity);
		return (M)this;
	}
	
	public java.lang.Integer getQuantity() {
		return getInt("quantity");
	}

	public M setOutType(java.lang.Integer outType) {
		set("out_type", outType);
		return (M)this;
	}
	
	public java.lang.Integer getOutType() {
		return getInt("out_type");
	}

	public M setTime(java.util.Date time) {
		set("time", time);
		return (M)this;
	}
	
	public java.util.Date getTime() {
		return get("time");
	}

	public M setOperator(java.lang.String operator) {
		set("operator", operator);
		return (M)this;
	}
	
	public java.lang.String getOperator() {
		return getStr("operator");
	}

	public M setBoxId(java.lang.Integer boxId) {
		set("box_id", boxId);
		return (M)this;
	}
	
	public java.lang.Integer getBoxId() {
		return getInt("box_id");
	}

}
