package com.jimi.uw_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({ "serial", "unchecked" })
public abstract class BaseMaterialBox<M extends BaseMaterialBox<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M) this;
	}


	public java.lang.Integer getId() {
		return getInt("id");
	}


	public M setArea(java.lang.String area) {
		set("area", area);
		return (M) this;
	}


	public java.lang.String getArea() {
		return getStr("area");
	}


	public M setRow(java.lang.Integer row) {
		set("row", row);
		return (M) this;
	}


	public java.lang.Integer getRow() {
		return getInt("row");
	}


	public M setCol(java.lang.Integer col) {
		set("col", col);
		return (M) this;
	}


	public java.lang.Integer getCol() {
		return getInt("col");
	}


	public M setHeight(java.lang.Integer height) {
		set("height", height);
		return (M) this;
	}


	public java.lang.Integer getHeight() {
		return getInt("height");
	}


	public M setIsOnShelf(java.lang.Boolean isOnShelf) {
		set("is_on_shelf", isOnShelf);
		return (M) this;
	}


	public java.lang.Boolean getIsOnShelf() {
		return get("is_on_shelf");
	}


	public M setEnabled(java.lang.Boolean enabled) {
		set("enabled", enabled);
		return (M) this;
	}


	public java.lang.Boolean getEnabled() {
		return get("enabled");
	}


	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M) this;
	}


	public java.lang.Integer getType() {
		return getInt("type");
	}


	public M setSupplier(java.lang.Integer supplier) {
		set("supplier", supplier);
		return (M) this;
	}


	public java.lang.Integer getSupplier() {
		return getInt("supplier");
	}


	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M) this;
	}


	public java.lang.Integer getStatus() {
		return getInt("status");
	}


	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M) this;
	}


	public java.util.Date getUpdateTime() {
		return get("update_time");
	}


	public M setCompanyId(java.lang.Integer companyId) {
		set("company_id", companyId);
		return (M) this;
	}


	public java.lang.Integer getCompanyId() {
		return getInt("company_id");
	}

}
