package com.jimi.uw_server.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTask<M extends BaseTask<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setFileName(java.lang.String fileName) {
		set("file_name", fileName);
		return (M)this;
	}
	
	public java.lang.String getFileName() {
		return getStr("file_name");
	}

	public M setWindow(java.lang.Integer window) {
		set("window", window);
		return (M)this;
	}
	
	public java.lang.Integer getWindow() {
		return getInt("window");
	}

	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

	public M setPriority(java.lang.Integer priority) {
		set("priority", priority);
		return (M)this;
	}
	
	public java.lang.Integer getPriority() {
		return getInt("priority");
	}

	public M setStartTime(java.util.Date startTime) {
		set("start_time", startTime);
		return (M)this;
	}
	
	public java.util.Date getStartTime() {
		return get("start_time");
	}

	public M setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
		return (M)this;
	}
	
	public java.util.Date getEndTime() {
		return get("end_time");
	}

	public M setCheckedOperatior(java.lang.String checkedOperatior) {
		set("checked_operatior", checkedOperatior);
		return (M)this;
	}
	
	public java.lang.String getCheckedOperatior() {
		return getStr("checked_operatior");
	}

	public M setCheckedTime(java.util.Date checkedTime) {
		set("checked_time", checkedTime);
		return (M)this;
	}
	
	public java.util.Date getCheckedTime() {
		return get("checked_time");
	}

	public M setChecked(java.lang.Boolean checked) {
		set("checked", checked);
		return (M)this;
	}
	
	public java.lang.Boolean getChecked() {
		return get("checked");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setSupplier(java.lang.Integer supplier) {
		set("supplier", supplier);
		return (M)this;
	}
	
	public java.lang.Integer getSupplier() {
		return getInt("supplier");
	}

	public M setDestination(java.lang.Integer destination) {
		set("destination", destination);
		return (M)this;
	}
	
	public java.lang.Integer getDestination() {
		return getInt("destination");
	}

	public M setIsInventoryApply(java.lang.Boolean isInventoryApply) {
		set("is_inventory_apply", isInventoryApply);
		return (M)this;
	}
	
	public java.lang.Boolean getIsInventoryApply() {
		return get("is_inventory_apply");
	}

	public M setInventoryTaskId(java.lang.Integer inventoryTaskId) {
		set("inventory_task_id", inventoryTaskId);
		return (M)this;
	}
	
	public java.lang.Integer getInventoryTaskId() {
		return getInt("inventory_task_id");
	}

}
