package com.jimi.uw_server.model;

import com.jimi.uw_server.model.base.BaseBoxPositionTaskItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BoxPositionTaskItem extends BaseBoxPositionTaskItem<BoxPositionTaskItem> {
	public static final BoxPositionTaskItem dao = new BoxPositionTaskItem().dao();
}
