package com.jimi.uw_server.model;

import com.jimi.uw_server.model.base.BaseBoxPositionTask;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BoxPositionTask extends BaseBoxPositionTask<BoxPositionTask> {
	public static final BoxPositionTask dao = new BoxPositionTask().dao();
}
