package com.jimi.uw_server.model;

import com.jimi.uw_server.model.base.BaseBoxType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BoxType extends BaseBoxType<BoxType> {
	public static final BoxType dao = new BoxType().dao();
}
