package com.jimi.uw_server.model;

import com.jimi.uw_server.model.base.BaseDestination;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Destination extends BaseDestination<Destination> {
	public static final Destination dao = new Destination().dao();
}
