package com.jimi.uw_server.model;

import com.jimi.uw_server.model.base.BaseEfficiency;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Efficiency extends BaseEfficiency<Efficiency> {
	public static final Efficiency dao = new Efficiency().dao();
}
