package com.jimi.uw_server.model;

import com.jimi.uw_server.model.base.BaseExternalInventoryLog;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExternalInventoryLog extends BaseExternalInventoryLog<ExternalInventoryLog> {

	public static final ExternalInventoryLog dao = new ExternalInventoryLog().dao();
}
