package com.jimi.uw_server.model;

import com.jimi.uw_server.model.base.BaseExternalWhLog;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExternalWhLog extends BaseExternalWhLog<ExternalWhLog> {

	public static final ExternalWhLog dao = new ExternalWhLog().dao();
}
