package com.jimi.uw_server.model;

import com.jimi.uw_server.model.base.BaseFaq;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Faq extends BaseFaq<Faq> {
	public static final Faq dao = new Faq().dao();
}
