package com.jimi.uw_server.model;

import com.jimi.uw_server.model.base.BaseFormerSupplier;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FormerSupplier extends BaseFormerSupplier<FormerSupplier> {
	public static final FormerSupplier dao = new FormerSupplier().dao();
}
