package com.jimi.uw_server.model;

import com.jimi.uw_server.model.base.BaseGoodsLocation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodsLocation extends BaseGoodsLocation<GoodsLocation> {
	public static final GoodsLocation dao = new GoodsLocation().dao();
}
