package com.jimi.uw_server.model;

import com.jimi.uw_server.model.base.BaseInputHelpSocketLog;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InputHelpSocketLog extends BaseInputHelpSocketLog<InputHelpSocketLog> {

	public static final InputHelpSocketLog dao = new InputHelpSocketLog().dao();
}
