package com.jimi.uw_server.model;

import com.jimi.uw_server.model.base.BaseInventoryTaskBaseInfo;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InventoryTaskBaseInfo extends BaseInventoryTaskBaseInfo<InventoryTaskBaseInfo> {

	public static final InventoryTaskBaseInfo dao = new InventoryTaskBaseInfo().dao();
}
