package com.jimi.uw_server.model;

import com.jimi.uw_server.model.base.BaseInventoryLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InventoryLog extends BaseInventoryLog<InventoryLog> {
	public static final InventoryLog dao = new InventoryLog().dao();
}
