package com.jimi.uw_server.model;

import com.jimi.uw_server.model.base.BaseMaterialBoxDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialBoxDetail extends BaseMaterialBoxDetail<MaterialBoxDetail> {
	public static final MaterialBoxDetail dao = new MaterialBoxDetail().dao();
}
