package com.jimi.uw_server.model;

import com.jimi.uw_server.model.base.BaseMaterialReturnRecord;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialReturnRecord extends BaseMaterialReturnRecord<MaterialReturnRecord> {

	public static final MaterialReturnRecord dao = new MaterialReturnRecord().dao();
}
