package com.jimi.uw_server.model;

import com.jimi.uw_server.model.base.BaseMaterialBox;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialBox extends BaseMaterialBox<MaterialBox> {
	public static final MaterialBox dao = new MaterialBox().dao();
}
