package com.jimi.uw_server.model;

import com.jimi.uw_server.model.base.BasePdaUploadLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PdaUploadLog extends BasePdaUploadLog<PdaUploadLog> {
	public static final PdaUploadLog dao = new PdaUploadLog().dao();
}
