package com.jimi.uw_server.model;

import com.jimi.uw_server.model.base.BaseSampleOutRecord;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SampleOutRecord extends BaseSampleOutRecord<SampleOutRecord> {

	public static final SampleOutRecord dao = new SampleOutRecord().dao();
}
