package com.jimi.uw_server.model;

import com.jimi.uw_server.model.base.BaseSampleSingularRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SampleSingularRecord extends BaseSampleSingularRecord<SampleSingularRecord> {
	public static final SampleSingularRecord dao = new SampleSingularRecord().dao();
}
