package com.jimi.uw_server.model;

import com.jimi.uw_server.model.base.BaseSampleTaskItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SampleTaskItem extends BaseSampleTaskItem<SampleTaskItem> {
	public static final SampleTaskItem dao = new SampleTaskItem().dao();
}
