package com.jimi.uw_server.model;

import com.jimi.uw_server.model.base.BaseSampleTaskMaterialRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SampleTaskMaterialRecord extends BaseSampleTaskMaterialRecord<SampleTaskMaterialRecord> {
	public static final SampleTaskMaterialRecord dao = new SampleTaskMaterialRecord().dao();
}
