package com.jimi.agv.tracker.entity.model;

import com.jimi.agv.tracker.entity.model.base.BaseTraditionBody;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TraditionBody extends BaseTraditionBody<TraditionBody> {
	public static final TraditionBody dao = new TraditionBody().dao();
}
