package com.jimi.agv.tracker.entity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTraditionBody<M extends BaseTraditionBody<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setTraditionHead(java.lang.Long traditionHead) {
		set("tradition_head", traditionHead);
		return (M)this;
	}
	
	public java.lang.Long getTraditionHead() {
		return getLong("tradition_head");
	}
	
	public M setRobotId(java.lang.Integer robotId) {
		set("robot_id", robotId);
		return (M)this;
	}
	
	public java.lang.Integer getRobotId() {
		return getInt("robot_id");
	}

	public M setTargetPosition(java.lang.String targetPosition) {
		set("target_position", targetPosition);
		return (M)this;
	}
	
	public java.lang.String getTargetPosition() {
		return getStr("target_position");
	}

	public M setAssignTime(java.util.Date assignTime) {
		set("assign_time", assignTime);
		return (M)this;
	}
	
	public java.util.Date getAssignTime() {
		return get("assign_time");
	}

	public M setStartTime(java.util.Date startTime) {
		set("start_time", startTime);
		return (M)this;
	}
	
	public java.util.Date getStartTime() {
		return get("start_time");
	}

	public M setGotTime(java.util.Date gotTime) {
		set("got_time", gotTime);
		return (M)this;
	}
	
	public java.util.Date getGotTime() {
		return get("got_time");
	}

	public M setArriveTime(java.util.Date arriveTime) {
		set("arrive_time", arriveTime);
		return (M)this;
	}
	
	public java.util.Date getArriveTime() {
		return get("arrive_time");
	}

	public M setReturnTime(java.util.Date returnTime) {
		set("return_time", returnTime);
		return (M)this;
	}
	
	public java.util.Date getReturnTime() {
		return get("return_time");
	}

	public M setFinishTime(java.util.Date finishTime) {
		set("finish_time", finishTime);
		return (M)this;
	}
	
	public java.util.Date getFinishTime() {
		return get("finish_time");
	}

	public M setGotConsumeTime(java.lang.Integer gotConsumeTime) {
		set("got_consume_time", gotConsumeTime);
		return (M)this;
	}
	
	public java.lang.Integer getGotConsumeTime() {
		return getInt("got_consume_time");
	}

	public M setTransportConsumeTime(java.lang.Integer transportConsumeTime) {
		set("transport_consume_time", transportConsumeTime);
		return (M)this;
	}
	
	public java.lang.Integer getTransportConsumeTime() {
		return getInt("transport_consume_time");
	}

	public M setReturnConsumeTime(java.lang.Integer returnConsumeTime) {
		set("return_consume_time", returnConsumeTime);
		return (M)this;
	}
	
	public java.lang.Integer getReturnConsumeTime() {
		return getInt("return_consume_time");
	}

	public M setGotTrails(java.lang.String gotTrails) {
		set("got_trails", gotTrails);
		return (M)this;
	}
	
	public java.lang.String getGotTrails() {
		return getStr("got_trails");
	}

	public M setTransportTrails(java.lang.String transportTrails) {
		set("transport_trails", transportTrails);
		return (M)this;
	}
	
	public java.lang.String getTransportTrails() {
		return getStr("transport_trails");
	}

	public M setReturnTrails(java.lang.String returnTrails) {
		set("return_trails", returnTrails);
		return (M)this;
	}
	
	public java.lang.String getReturnTrails() {
		return getStr("return_trails");
	}

}
