package com.jimi.uw_server.constant.sql;

public class IOTaskSQL {

	public static final String GET_PACKING_LIST_ITEM_BY_TASKID = "SELECT * FROM packing_list_item WHERE packing_list_item.task_id = ?";

	public static final String GET_PACKING_LIST_ITEM_BY_TASKID_AND_NO = "SELECT packing_list_item.* FROM packing_list_item INNER JOIN material_type ON packing_list_item.material_type_id = material_type.id WHERE packing_list_item.task_id = ? AND material_type.`no` = ? AND material_type.type = ? AND material_type.enabled = 1";

	public static final String GET_OLDER_MATERIAL_BY_BOX_AND_TIME = "select * from material where type = ? and production_time < ? and remainder_quantity > 0 and status = ? ORDER BY production_time asc";

	public static final String GET_OLDER_MATERIAL_BY_BOX_AND_TIME_AND_NOTNULLCYCLE = "select * from material where type = ? and production_time < ? and remainder_quantity > 0 and status = ? and cycle is not null ORDER BY production_time asc";

	public static final String GET_OUT_MATERIAL_BY_ITEM_ID_SQL = "SELECT task_log.id, material_id AS materialId, quantity, production_time AS productionTime, is_in_box AS isInBox, remainder_quantity  AS remainderQuantity FROM task_log JOIN material ON  task_log.material_id = material.id WHERE task_log.packing_list_item_id = ? ORDER BY task_log.id DESC";

	public static final String GET_PRECIOUS_IOTASK_INFOS = "SELECT A.*, B.* FROM ( SELECT packing_list_item.material_type_id AS PackingListItem_MaterialTypeId, packing_list_item.id AS PackingListItem_Id, packing_list_item.task_id AS PackingListItem_TaskId, packing_list_item.quantity AS PackingListItem_Quantity, packing_list_item.finish_time AS PackingListItem_FinishTime, material_type.type AS MaterialType_Type, material_type.enabled AS MaterialType_Enabled, material_type.id AS MaterialType_Id, material_type.supplier AS MaterialType_Supplier, material_type. NO AS MaterialType_No, material_type.specification AS MaterialType_Specification, material_type.thickness AS MaterialType_Thickness, material_type.radius AS MaterialType_Radius, material_type.designator AS MaterialType_Designator, supplier. NAME AS Supplier_Name, supplier.enabled AS Supplier_Enabled, supplier.id AS Supplier_Id FROM packing_list_item JOIN material_type JOIN supplier ON packing_list_item.material_type_id = material_type.id AND material_type.supplier = supplier.id WHERE packing_list_item.task_id = ? AND packing_list_item.finish_time IS NULL ) A LEFT JOIN (SELECT task_log.time AS TaskLog_Time, task_log.id AS TaskLog_Id, task_log.packing_list_item_id AS TaskLog_PackingListItemId, task_log.quantity AS TaskLog_Quantity, task_log.destination AS TaskLog_Destination, task_log.material_id AS TaskLog_MaterialId, task_log.operator AS TaskLog_Operator, material.remainder_quantity AS Material_RemainderQuantity, material.production_time AS Material_ProductionTime, material.`status` AS Material_Status  FROM task_log INNER JOIN material INNER JOIN packing_list_item ON task_log.material_id = material.id AND task_log.packing_list_item_id = packing_list_item.id WHERE packing_list_item.task_id = ? ) B ON A.PackingListItem_Id = B.TaskLog_PackingListItemId ORDER BY A.PackingListItem_Id ASC";

	public static final String GET_PRECIOUS_IO_TASK_UW_STORE = "SELECT packing_list_item.id AS PackingListItem_Id, SUM(material.remainder_quantity) AS uwStore FROM packing_list_item JOIN material ON packing_list_item.material_type_id = material.type WHERE packing_list_item.task_id = ? AND material.remainder_quantity > 0 AND material.`status` = 0 GROUP BY material.type";

	public static final String GET_PROBLEM_IOTASK_ITEM_BY_TASK_ID = "SELECT packing_list_item.id AS PackingListItem_Id, packing_list_item.quantity AS PlanQuantity, SUM(task_log.quantity) AS actuallyQuantity FROM packing_list_item LEFT JOIN task_log  ON packing_list_item.id = task_log.packing_list_item_id  WHERE packing_list_item.task_id = ? GROUP BY packing_list_item.id HAVING SUM(task_log.quantity) < packing_list_item.quantity OR SUM(task_log.quantity) IS NULL";

	public static final String GET_CAN_FINSH_IOTASK_ITEM_BY_TASK_ID = "SELECT packing_list_item.* FROM packing_list_item INNER JOIN task_log ON packing_list_item.id = task_log.packing_list_item_id WHERE packing_list_item.task_id = ? AND packing_list_item.finish_time IS NULL GROUP BY packing_list_item.id HAVING SUM(task_log.quantity) = packing_list_item.quantity";

	public static final String GET_UNFINSH_PROBLEM_IOTASK_ITEM_BY_TASK_ID = "SELECT packing_list_item.id AS PackingListItem_Id, packing_list_item.quantity AS PlanQuantity, SUM(task_log.quantity) AS actuallyQuantity FROM packing_list_item LEFT JOIN task_log  ON packing_list_item.id = task_log.packing_list_item_id  WHERE packing_list_item.task_id = ? AND packing_list_item.finish_time IS NULL GROUP BY packing_list_item.id HAVING SUM(task_log.quantity) != packing_list_item.quantity OR SUM(task_log.quantity) IS NULL";

	public static final String GET_CUTTING_PACKING_LIST_ITEM_BY_TASK_ID = "SELECT packing_list_item.* FROM material INNER JOIN task_log INNER JOIN packing_list_item ON task_log.material_id = material.id AND packing_list_item.id = task_log.packing_list_item_id WHERE material.cut_task_log_id IS NOT NULL AND packing_list_item.task_id = ?";

	public static final String GET_IN_WRONG_IOTASK_ITEM_BY_TASK_ID = "SELECT packing_list_item.id AS PackingListItem_Id, packing_list_item.quantity AS PlanQuantity, SUM(task_log.quantity) AS actuallyQuantity FROM packing_list_item LEFT JOIN task_log  ON packing_list_item.id = task_log.packing_list_item_id  WHERE packing_list_item.task_id = ? AND packing_list_item.finish_time IS NULL GROUP BY packing_list_item.id HAVING SUM(task_log.quantity) != packing_list_item.quantity";

	public static final String GET_OUT_OVER_PRECIOUS_IOTASK_ITEM_BY_TASKID = "SELECT packing_list_item.id AS PackingListItem_Id, packing_list_item.quantity AS PlanQuantity, SUM(task_log.quantity) AS actuallyQuantity FROM packing_list_item LEFT JOIN task_log  ON packing_list_item.id = task_log.packing_list_item_id  WHERE packing_list_item.task_id = ? AND packing_list_item.finish_time IS NULL HAVING SUM(task_log.quantity) > packing_list_item.quantity";

	public static final String GET_OUT_LACK_PRECIOUS_IOTASK_ITEM_BY_TASKID = "SELECT packing_list_item.id AS PackingListItem_Id, packing_list_item.quantity AS PlanQuantity, SUM(task_log.quantity) AS actuallyQuantity FROM packing_list_item LEFT JOIN task_log  ON packing_list_item.id = task_log.packing_list_item_id  WHERE packing_list_item.task_id = ? AND packing_list_item.finish_time IS NULL HAVING SUM(task_log.quantity) < packing_list_item.quantity AND sum(task_log.quantity) != 0";

	public static final String GET_IOTASK_CUTTING_PACKING_LIST_ITEM = "SELECT packing_list_item.id AS PackingListItem_Id FROM material INNER JOIN packing_list_item INNER JOIN task_log ON task_log.material_id = material.id AND packing_list_item.id = task_log.packing_list_item_id AND task_log.id = material.cut_task_log_id WHERE packing_list_item.task_id = ? AND material.status = 1";

	public static final String GET_IOTASK_CUTTING_PACKING_LIST_ITEM_BY_ID = "SELECT packing_list_item.id AS PackingListItem_Id FROM material INNER JOIN packing_list_item INNER JOIN task_log ON task_log.material_id = material.id AND packing_list_item.id = task_log.packing_list_item_id  AND task_log.id = material.cut_task_log_id WHERE packing_list_item.id = ? AND material.status = 1";

	public static final String GET_DIFFERENCE_QUANTITY_OF_IOTASK = "select material.id, (material.remainder_quantity - task_log.quantity) AS quantity from task_log INNER JOIN material INNER JOIN packing_list_item ON packing_list_item.id = task_log.packing_list_item_id AND task_log.material_id = material.id WHERE packing_list_item.task_id = ? AND packing_list_item.finish_time IS NULL";

	public static final String GET_ALL_UNFINISH_PRECIOUS_IOTASK_ITEM = "SELECT * FROM packing_list_item WHERE packing_list_item.task_id = ? AND packing_list_item.finish_time IS NULL ";

	public static final String GET_PROBLEM_PRECIOUS_IOTASK_ITEM_BY_ID = "SELECT packing_list_item.id AS PackingListItem_Id, packing_list_item.quantity AS PlanQuantity, SUM(task_log.quantity) AS actuallyQuantity FROM packing_list_item LEFT JOIN task_log  ON packing_list_item.id = task_log.packing_list_item_id  WHERE packing_list_item.id = ? HAVING SUM(task_log.quantity) > packing_list_item.quantity";

	public static final String GET_UNFINISH_PRECIOUS_IOTASK_ITEM_BY_TASK_ID = "SELECT packing_list_item.id AS PackingListItem_Id, packing_list_item.quantity AS PlanQuantity, SUM(task_log.quantity) AS actuallyQuantity FROM packing_list_item LEFT JOIN task_log ON packing_list_item.id = task_log.packing_list_item_id WHERE packing_list_item.task_id = ? GROUP BY packing_list_item.id HAVING SUM(task_log.quantity) != packing_list_item.quantity OR SUM(task_log.quantity) IS NULL";

	public static final String GET_MATERIAL_AND_OUTQUANTITY_BY_PACKING_LIST_ITEM_ID = "SELECT material.*, task_log.quantity AS outQuantity FROM material INNER JOIN task_log ON task_log.material_id = material.id WHERE task_log.packing_list_item_id = ?";

	public static final String GET_MATERIAL_BY_PACKING_LIST_ITEM_ID = "SELECT material.* FROM material INNER JOIN task_log ON task_log.material_id = material.id WHERE task_log.packing_list_item_id = ?";

	public static final String GET_UNFINISH_PACKING_LIST_ITEM = "SELECT * FROM packing_list_item WHERE packing_list_item.task_id = ? AND packing_list_item.finish_time IS NULL";

	public static final String GET_OLDEST_MATERIAL_UW_STORE = "SELECT material.*, packing_list_item.id AS PackingListItem_Id FROM material INNER JOIN packing_list_item ON packing_list_item.material_type_id = material.type WHERE remainder_quantity > 0 AND packing_list_item.task_id = ? AND status = 0 ORDER BY type, production_time ASC";

	public static final String GET_TASK_BY_NAME = "SELECT * FROM task WHERE task.file_name = ? and task.state != ?";

	public static final String GET_OUT_QUANTIYT_IOTASK_ITEM_BY_ID = "SELECT packing_list_item.id AS PackingListItem_Id, packing_list_item.quantity AS PlanQuantity, SUM(task_log.quantity) AS ActualQuantity, task_log.operator AS Operator FROM packing_list_item LEFT JOIN task_log  ON packing_list_item.id = task_log.packing_list_item_id  WHERE packing_list_item.id = ?";

	public static final String GET_MATERIAL_ID_IN_SAME_TASK_SQL = "SELECT * FROM task_log WHERE material_id = ? AND packing_list_item_id = ?";

	public static final String GET_TASK_ITEM_DETAILS_SQL = "SELECT material_id AS materialId, quantity, production_time AS productionTime FROM task_log JOIN material ON task_log.packing_list_item_id = ? AND task_log.material_id = material.id";

	public static final String DELETE_TASK_LOG_SQL = "DELETE FROM task_log WHERE packing_list_item_id = ? AND material_id = ?";

	public static final String GET_TASK_LOG_BY_PACKING_LIST_ITEM_ID_AND_MATERIAL_ID_SQL = "SELECT * FROM task_log WHERE packing_list_item_id = ? AND material_id = ?";

	public static final String GET_TASK_BY_TYPE = "SELECT * FROM task WHERE task.type = ? AND task.state = ? AND warehouse_type = ?";

	public static final String GET_CUTTING_MATERIAL_SQL = "SELECT material.id as materialId, material.remainder_quantity AS materialQuantity, task_log.quantity AS outQuantity, material.manufacturer AS manufacturer, material.production_time AS productionTime , material.cycle AS cycle, material_type.`no` AS `no`, material_type.specification AS specification, supplier.`name` AS supplierName, task_log.packing_list_item_id AS packingListItemId, task_log.id AS taskLogId FROM material INNER JOIN material_type INNER JOIN supplier INNER JOIN task_log ON material.type = material_type.id AND material_type.supplier = supplier.id AND material.cut_task_log_id = task_log.id WHERE material.status = ? AND material.remainder_quantity > 0 AND material_type .type = ? AND material_type.enabled = 1 AND supplier.enabled = 1";

	public static final String GET_ALL_SUM_OF_TASK_LOG_BY_TIME_AND_MATERIALTYPE_SQL = "SELECT A.* FROM (( SELECT SUM(task_log.quantity) AS IO_Quantity, task.type AS Task_Type, packing_list_item.finish_time AS Time FROM task_log INNER JOIN packing_list_item INNER JOIN task ON task.id = packing_list_item.task_id AND packing_list_item.id = task_log.packing_list_item_id WHERE packing_list_item.finish_time BETWEEN ? AND ? AND packing_list_item.material_type_id = ? GROUP BY packing_list_item_id ) UNION ALL ( SELECT sum( inventory_log.actural_num - inventory_log.before_num ) AS IO_Quantity, 2 AS Task_Type, inventory_log.inventory_time AS Time FROM inventory_log INNER JOIN task INNER JOIN material ON task.id = inventory_log.task_id AND material.id = inventory_log.material_id WHERE inventory_log.inventory_time BETWEEN ? AND ? AND material.type = ? GROUP BY task.id, material.type ) UNION ALL ( SELECT sum(sample_out_record.quantity) AS IO_Quantity, 7 AS Task_Type, sample_out_record.time AS Time FROM sample_out_record INNER JOIN sample_task_item ON sample_task_item.id = sample_out_record.sample_task_item_id WHERE sample_out_record.time BETWEEN ? AND ? AND sample_task_item.material_type_id = ? GROUP BY sample_task_item.task_id, sample_task_item.material_type_id )) A ORDER BY A.Time ASC";

	public static final String GET_UW_STOCK_BY_TIME_AND_MATERIALTYPE_SQL = "SELECT SUM(A.IO_Quantity) AS IO_Quantity FROM (( SELECT SUM(task_log.quantity) AS IO_Quantity FROM task_log INNER JOIN packing_list_item INNER JOIN task ON task.id = packing_list_item.task_id AND packing_list_item.id = task_log.packing_list_item_id WHERE packing_list_item.finish_time < ? AND packing_list_item.material_type_id = ? AND (task.type = 0 || task.type = 4) GROUP BY packing_list_item.material_type_id ) UNION ALL ( SELECT (0 - SUM(task_log.quantity)) AS IO_Quantity FROM task_log INNER JOIN packing_list_item INNER JOIN task ON task.id = packing_list_item.task_id AND packing_list_item.id = task_log.packing_list_item_id WHERE packing_list_item.finish_time < ? AND packing_list_item.material_type_id = ? AND (task.type = 1 || task.type = 8) GROUP BY packing_list_item.material_type_id ) UNION ALL ( SELECT sum( inventory_log.actural_num - inventory_log.before_num ) AS IO_Quantity FROM inventory_log INNER JOIN task INNER JOIN material ON task.id = inventory_log.task_id AND material.id = inventory_log.material_id WHERE inventory_log.inventory_time < ? AND material.type = ? GROUP BY material.type ) UNION ALL ( SELECT sum(sample_out_record.quantity) AS IO_Quantity FROM sample_out_record INNER JOIN sample_task_item ON sample_task_item.id = sample_out_record.sample_task_item_id WHERE sample_out_record.time < ? AND sample_task_item.material_type_id = ? GROUP BY sample_task_item.material_type_id )) A";

	public static final String GET_ALL_EXTERNAL_WH_IO_LOG_BY_TIME_AND_MATERIALTYPE_SQL = "SELECT A.* FROM (( SELECT SUM(external_wh_log.quantity) AS IO_Quantity, task.type AS Task_Type, external_wh_log.operation_time AS Time FROM external_wh_log INNER JOIN task ON task.id = external_wh_log.task_id WHERE task.type = 4 AND source_wh = ? AND external_wh_log.operation_time BETWEEN ? AND ? AND external_wh_log.material_type_id = ? GROUP BY task.id, external_wh_log.material_type_id ) UNION ALL ( SELECT SUM(external_wh_log.quantity) AS IO_Quantity, task.type AS Task_Type, external_wh_log.operation_time AS Time FROM external_wh_log INNER JOIN task ON task.id = external_wh_log.task_id WHERE ( task.type = 1 OR task.type = 2 OR task.type = 6 OR task.type = 5 OR task.type = 8 ) AND external_wh_log.destination = ? AND external_wh_log.operation_time BETWEEN ? AND ? AND external_wh_log.material_type_id = ? GROUP BY task.id, external_wh_log.material_type_id ) UNION ALL ( SELECT ( 0 - SUM(external_wh_log.quantity)) AS IO_Quantity, task.type AS Task_Type, external_wh_log.operation_time AS Time FROM external_wh_log INNER JOIN task ON task.id = external_wh_log.task_id WHERE task.type = 5 AND external_wh_log.source_wh = ? AND external_wh_log.operation_time BETWEEN ? AND ? AND external_wh_log.material_type_id = ? GROUP BY task.id, external_wh_log.material_type_id )) A ORDER BY A.Time";

}
