package com.jimi.agv.tracker.entity.model;

import com.jimi.agv.tracker.entity.model.base.BaseCushionHead;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CushionHead extends BaseCushionHead<CushionHead> {
	public static final CushionHead dao = new CushionHead().dao();
}
