package com.jimi.agv.tracker.entity.model;

import com.jimi.agv.tracker.entity.model.base.BaseCushionBody;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CushionBody extends BaseCushionBody<CushionBody> {
	public static final CushionBody dao = new CushionBody().dao();
}
