package com.jimi.agv.tracker.entity.model;

import com.jimi.agv.tracker.entity.model.base.BaseTraditionHead;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TraditionHead extends BaseTraditionHead<TraditionHead> {
	public static final TraditionHead dao = new TraditionHead().dao();
}
